source 'https://rubygems.org'

gem 'rails', '4.0.2'
#PostgreSQL
gem 'pg', '~> 0.17.1'

group :assets do
  gem 'sass-rails', '~> 4.0.0'
  gem 'uglifier', '~> 2.4.0'
  gem 'coffee-rails', '~> 4.0.0'
end

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

group :test, :development do
  gem 'rspec-rails', '~> 2.14.1'
end

group :test do
  gem 'capybara', '~> 2.2.1'
  gem 'factory_girl_rails', '~> 4.3.0'
end

group :doc do
  gem 'sdoc', require: false
end
